name: "JFrog CLI Example"
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container: golang:1.14-alpine
    steps:
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v1
        env:
          JF_ARTIFACTORY_SERVER: ${{ secrets.JF_RT_ECO }}
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: jfrog/jfrog-cli 
      - name: Build
        run: |
          go version
      - name: Run JFrog CLI
        run: |
          pwd
          ls -l
          # Collect environment variables for the build
          jfrog rt bce
          # Collect VCS details from git and add them to the build
          jfrog rt bag
          # Publish build info
          jfrog rt bp
