name: "JFrog CLI Example"
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container: amd64/golang:latest
    steps:
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v1
        env:
          JF_ARTIFACTORY_SERVER: ${{ secrets.JF_RT_ECO }}
      - name: Checkout
        run: git clone https://github.com/jfrog/jfrog-cli.git
      - name: Build
        run: |
          cd jfrog-cli
          # Build the code
          jfrog rt go-config --server-id-resolve eco --repo-resolve go
          export CGO_ENABLED=0
          jfrog rt go build -o jfrog -ldflags '-w -extldflags "-static"' main.go --module "JFrog CLI Example"
          # Get the version
          version=$(./jfrog -v | cut -d " " -f 3)
          echo Build JFrog CLI version $version
          # Upload the jfrog-cli binary
          jfrog rt u jfrog rc-local/jfrog-cli-releases/$version/
          # Add env vars
          jfrog rt bce
          # Add git info
          jfrog rt bag
          # Publish build-info
          jfrog rt bp
          # Scan build with JFrog Xray
          jfrog rt bs --fail=false
          # Promote build to staging
          jfrog rt bpr
